#! /usr/bin/perl
use warnings;
use strict;
use Minivan;

my $van = Minivan->new(host => 'localhost'); # port => 6826 is the default
$van->subscribe("c1");
while (1) {
	my @m = $van->get;
	for (@m) {
		print "$_\n";
	}
	sleep 1;
}
